### ISSUE TITLE
Lỗi node .

### ISSUE THREAD

**Issue by NOTAD** [lyminhnghia/Caro-Online-Server#1]
Caro-Online-Server-master$ node .
url.js:154
    throw new ERR_INVALID_ARG_TYPE('url', 'string', url);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
    at Url.parse (url.js:154:11)
    at Object.urlParse [as parse] (url.js:148:13)
    at new Sequelize (/home/lehongson/Desktop/Caro-Online-Server-master/node_modules/sequelize/lib/sequelize.js:187:28)
    at Object.<anonymous> (/home/lehongson/Desktop/Caro-Online-Server-master/configs/db.config.js:9:17)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/lehongson/Desktop/Caro-Online-Server-master/routes/verifyJwtToken.js:2:12)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at module.exports (/home/lehongson/Desktop/Caro-Online-Server-master/routes/route.js:2:33)
    at Object.<anonymous> (/home/lehongson/Desktop/Caro-Online-Server-master/index.js:12:26)
    at Module._compile (internal/modules/cjs/loader.js:701:30)

**Comment by lyminhnghia** [comment]
This problem is because you have not created a .env file yet
Solve: 
1) Create file .env in folder Caro-Online-Server-master
2) In .env add 
DATABASE_URL = mysql://<username>:<password>@127.0.0.1:3306/<database>
with <username> && <password>: your user, password in sql
<database>: database name
